version: "3.9"

services:

  dev-desktop:
    build: .
    container_name: dev-desktop

    ports:
      - "6080:6901"
      - "8080:8080"

    environment:
      - VNC_PW=password123
      - PASSWORD=password123

    volumes:
      - ./workspace:/workspace
      - ollama:/root/.ollama

    restart: unless-stopped

volumes:
  ollama: