FROM accetto/ubuntu-vnc-xfce-g3:24.04

USER root

RUN apt-get update && apt-get install -y \
    openjdk-21-jdk \
    python3 \
    python3-pip \
    python3-venv \
    git \
    curl \
    wget \
    build-essential \
    firefox \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*


# python alias
RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /workspace